### ISSUE TITLE
Target Attention in generated long lookup tables

### ISSUE THREAD

**Issue by mitjanikolaus** [i-machine-think/machine-tasks#11]
It would be nice to also have the target attention (third column) automatically in the tables generated with [make_lookup_tables.py](https://github.com/i-machine-think/machine-tasks/blob/master/LongLookupTables/make_lookup_tables.py).

These should be simply ascending numbers (for example the "012" in the first row in https://github.com/i-machine-think/machine-tasks/blob/master/LookupTables/lookup-3bit/samples/sample1/train.tsv)

**Comment by mitjanikolaus** [comment]
just found out that this can be also added using the other [script](https://github.com/i-machine-think/machine-tasks/blob/master/scripts/minor_data_modifications.py), so maybe it is not so important anymore

**Comment by YannDubs** [comment]
@dieuwkehupkes what should the target attention be when there's no copy step ? theoretically it should still attend to the input, but then the target attention is longer than the number of decoding steps. I'll still attend on input for now as it makes the most sense but then I'm not sure AG would actually work (without the ponderer). Any thoughts?

**Comment by YannDubs** [comment]
SImply used a NotImplementedError for the question above.
